Form/PostType.php
<?php

    namespace scrclub\CMSBundle\Form;

    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\FormBuilderInterface;
    use Symfony\Component\OptionsResolver\OptionsResolverInterface;
    use scrclub\CMSBundle\Entity\LangsRepository;
    use scrclub\CMSBundle\Entity\Template;

    class PostType extends NodeType
    {

        function __construct(\scrclub\CMSBundle\Entity\LangsRepository $langrepo, array $templates, Template $defaultTemplate) {
            $this->langrepo         = $langrepo;
            $this->templates        = $templates;
            $this->defaultTemplate  = $defaultTemplate;
        }

        public function setDefaultOptions(OptionsResolverInterface $resolver)
        {
            $resolver->setDefaults(array(
                'data_class' => 'scrclub\CMSBundle\Entity\Post'
            ));
        }

        public function getName()
        {
            return 'scrclub_cmsbundle_posttype';
        }
    }

Resources/views/cms/addEmbedPopover.html.twig
<div class="" id="embeddoc-modal-container">

    {{ form_errors(form) }}

    {{ getEmbed(document)}}

    <!-- <img src="{{ getThumbnail(document)}}"> -->
    <hr>

    <form id="embed-edit-form" action="{{ path('scrclub_cms_updateEmbedPopOver', {mediasetId:mediaset.id , id:document.id}) }}" method="post" {{ form_enctype(form) }} novalidate >
        {{form_widget(form)}}


        <script>

            console.log("set js");
            $('#media-form-submit').unbind('click');
            $('#media-form-submit').on('click', function(e){

                e.preventDefault();

                var options = {
                    success: function (responseText, statusText, xhr, $form) {

                        $('#embeddoc-modal-container').parent().html(responseText.html);
                        $('#media-form-submit').html("{{ 'save.changes'| trans  }}");

                    },
                    dataType:'json'
                };

                $('#embed-edit-form').ajaxSubmit(options);

                $('#media-form-submit').html('{{ 'save.changes'| trans  }} <i class="icon-refresh icon-spin"></i></a>');

            });

        </script>



</div>

Resources/views/cms/addpost.html.twig
{% extends "scrclubCMSBundle:cms:layout.html.twig" %}

{% block body %}


{% javascripts '@scrclubCMSBundle/Resources/public/js/cms/mediaset.js' filter='yui_js'  output='js/compiled/mediaset.js' %}
<script src="{{ asset_url }}"></script>
{% endjavascripts %}

{% javascripts '@scrclubCMSBundle/Resources/public/js/cms/edit-post.js' filter='yui_js'  output='js/compiled/cms.js' %}
<script src="{{ asset_url }}"></script>
{% endjavascripts %}



<div class="container post" id="{{node.id}}" xmlns="http://www.w3.org/1999/html">

<!-- got to node -->
<div class="nav-collapse">
    <ul class="nav">
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle active" href="#">Go To <b class="caret"></b></a>
            {% include 'scrclubCMSBundle:cms:nodeMenuChildren.html.twig' with {'tree':tree, 'level':0 } %}
        </li>
    </ul>
</div>


<div class="featurette">
    <h2 class="featurette-heading">{{ 'edit'| trans }} {{ 'post'| trans }} /
        <div class="muted featurette-sub-heading">{{ node.name }}</div>
    </h2>
</div>

<hr class="featurette-divider">


{% if form.get('errors') is not empty %}
<div class="row-fluid page-header">
    <div class="featurette">
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Error!</strong> {{form_errors(form)}}
        </div>
    </div>
</div>
{% endif %}


<form action="{{ path('scrclub_cms_addpost', { 'parent_id' : parent_id, 'id': node.id }) }}" method="post" {{ form_enctype(form) }} novalidate>
<div class="row-fluid page-header">
    <div class="featurette pull-right">



        <div id="active_box_button" class="switch switch-small">
            {{ form_widget(form.active, { 'attr': {'id': 'active_box'} }) }}
        </div>

        <span class="right-caret-btn"></span>
        <a alt="{{node.slug}}" href="#"><button class="btn"><i class="icon-search"> {{node.slug}}</i></button></a>

    </div>
</div>


{% set form_locales = form.translations.vars.locales %}
{% set fields = form.translations.fields %}

<div class="tabbable">
    <ul class="nav nav-tabs" id="langTab">


        {% for locale in form_locales %}


        {% set icon = '' %}

        {% if (form.translations.vars.default_locale[0] != locale)%}
        {% for translationForm in form.translations if (translationForm.vars.name == locale) %}

        {% if (translationForm.name.get('value') == "") %}

        {% set icon = '<i class="icon-warning-sign"></i>' %}

        {% endif %}
        {% endfor %}
        {% endif %}


        <li class="{% if (form.translations.vars.default_locale[0] == locale) %} active {% endif %}">
            <a href="#{{locale}}" data-toggle="tab">{{icon | raw}} {{getLocaleName(locale,  app.request.locale  ) | capitalize }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="tab-content">


    {% for locale in form_locales %}


    <div class="tab-pane x {% if (form.translations.vars.default_locale[0] == locale) %} active {% endif %}" id="{{locale}}">

        <fieldset>
            <div class=" well control-group">
                <div class="row-fluid">

                    {% if (form.translations.vars.default_locale[0] == locale) %}

                    <div class="span9">

                        {{ form_label( form.name , 'name' | lower | trans | capitalize , {'attr': {'class': 'input-xxlarge' }})
                        }}
                        {{ form_widget(form.name,  {'attr': {'class': 'input-xxlarge'}})}}


                        {{ form_label( form.description , 'description' | lower | trans | capitalize , {'attr': {'class': 'input-xxlarge' }})
                        }}
                        {{ form_widget(form.description,  {'attr': {'class': 'input-xxlarge text-area-high'}})}}


                    </div>

                    {% else %}

                    {% for translationForm in form.translations if (translationForm.vars.name == locale) %}

                    <div class="span9">

                        {% for f in translationForm.children %}

                        {{ form_label( f , f.name | lower | trans | capitalize , {'attr': {'class': 'input-xxlarge' }})
                        }}
                        {{ form_widget(f,  {'attr': {'class': 'input-xxlarge text-area-high'}})}}

                        {% endfor %}

                    </div>


                    {% endfor %}

                    {% endif %}

                </div>
            </div>
        </fieldset>

    </div>
    <script type="text/javascript">
        $(function () {

            $('#scrclub_cmsbundle_posttype_translations_{{locale}}_description').wysihtml5();

        })
    </script>

    {% endfor %}
</div>

<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="#">{{ 'template.settings'| trans  }}</a>
    </div>
</div>


<fieldset>
    <div class=" well control-group">
        <div class="row-fluid">

            <div class="span4">


                <label>{{ 'layouts'| trans  }}</label>
                {{ form_widget(form.template)}}
            </div>

            <div class="span3">
                <label>&nbsp;</label>
                <button type="submit" class="btn btn-primary">Preview</button>
            </div>


        </div>
    </div>


</fieldset>

<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="#">{{ 'categories'| trans  }}</a>
    </div>
</div>



<fieldset>
<div class=" well control-group">

    {{ form_widget(form.categories, { 'attr': {'class': 'input-xlarge populate placeholder category-select'}, 'empty_value': '' }) }}

</div>
</fieldset>





{% if node.id %}

<fieldset>
    <div class="navbar">
        <div class="navbar-inner">
            <a class="brand" href="#">{{ 'mediasets'| trans | capitalize }}</a>
            <ul class="nav" id="mediaset-tab">
                {% for mediaset in node.mediasets %}
                <li {% if loop.first %}class="active" {% endif %}>
                    <a href="#mediaset-{{mediaset.id}}">{{ mediaset.name }}</a></li>
                {% endfor %}
            </ul>
        </div>

    </div>

    <div class="tab-content">
        {% for mediaset in node.mediasets %}

        <div class="tab-pane {% if loop.first %}active{% endif %}" id="mediaset-{{mediaset.id}}">

            <ul class="nav nav-tabs">
                <li {% if loop.first %} class="active" {% endif %} >
                    <a href="#mediaset-node-{{mediaset.id}}" data-toggle="tab">Your post</a></li>
                <li><a href="#mediaset-all-{{mediaset.id}}" data-toggle="tab">All</a></li>
            </ul>

            <div class="tab-content">

                <div class="tab-pane active" id="mediaset-node-{{mediaset.id}}">

                    <ul class="media-post-container sortable-thumb thumbnails ">

                        {% for mediaNode in node.getMediaNodes() %}
                        {% if contains(mediaset, mediaNode.media.getMediaSets() ) %}
                        {% include 'scrclubCMSBundle:cms:list_image.html.twig' with {'mediaNode':mediaNode, 'mediaset':mediaset} %}
                        {% endif %}
                        {% endfor %}

                    </ul>
                </div>


                <div class="tab-pane " id="mediaset-all-{{mediaset.id}}">
                    <div class="row">
                        <div id="mediaset-upload-{{mediaset.id}}" class="span12"></div>

                    </div>
                    <hr>


                    <ul class="media-scroll-container thumbnails ">

                        {% for media in mediaset.medias %}

                        {% include 'scrclubCMSBundle:cms:list_image_mediaset.html.twig' with {'media':media, 'mediaset':mediaset} %}

                        {% endfor %}


                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>


</fieldset>

{%  else %}

<div class="alert alert-info"><i class=" icon-exclamation-sign"></i>{{ 'validate.post.media.notice'| trans | capitalize }}
</div>

{%  endif %}

{{ form_widget(form._token) }}
{{ form_widget(form.type)}}
<button type="submit" class=" btn btn-primary pull-right" id="validate_section">{% trans %}save.changes{% endtrans %}</button>


</form>


<div id="media-edit-modal" class="modal hide fade ">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Edit Image </h3>
    </div>
    <div class="modal-body">

    </div>
    <div class="modal-footer">
        <a href="#" data-dismiss="modal" aria-hidden="true" class="btn">Close</a>
        <button id="media-form-submit" type="submit" class=" btn btn-primary pull-right">{% trans %}save.changes{% endtrans %}</button>

    </div>
</div>


</div>
<!-- scripts -->

<script type="text/javascript">


    $(function () {

        $('#scrclub_cmsbundle_posttype_description').wysihtml5();

        {% for mediaset in node.mediasets %}
        createUploader({{mediaset.id}});
        {% endfor %}

        $(".category-select").select2({
                    placeholder :"{% trans %}choose.category{% endtrans %}"
                }
        );

    })


</script>


{% endblock %}

Resources/views/cms/adduser.html.twig
{% extends "scrclubCMSBundle:cms:config.html.twig" %}

{% block sub_body %}



<div class="featurette">
    <h2 class="featurette-heading">{{ 'user'| trans | capitalize }}  /<div class="muted featurette-sub-heading">{{ user.name }}</div></h2>
</div>

<hr class="featurette-divider">

{% for key, message in app.session.flashbag.all() %}
<div class="{{ key }}">
    {{ message }}
</div>
{% endfor %}

{% if form.points.vars.errors|length %}
<div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ form_errors(form) }}
    {{ error|trans({}, 'FOSUserBundle') }}
</div>
{% endif %}

<div class="span9">&nbsp;</div>
    <fieldset>
        <div class="well control-group">




    <form action="{{ path('scrclub_cms_adduser', {'id' : user.id }) }}" method="post" {{ form_enctype(form) }}>


        <div class="fileupload fileupload-new" data-provides="fileupload">
            <div class="fileupload-preview thumbnail" style="width: 200px; height: 150px;">
                <img  data-src="holder.js/200x150/text:Avatar" {% if (image.getWebPath() != "" )%}src="{{asset(image.getWebPath())}}" {% endif %}alt="">
            </div>
            <div>
                <span class="btn btn-file"><span class="fileupload-new">Select image</span><span class="fileupload-exists">Change</span>{{ form_widget(form.image.file)}}</span>
            </div>
        </div>

        <hr>


        {{ form_label( form.username , 'name' | lower | trans | capitalize , {'attr': {'class': 'input-xxlarge' }}) }}
        {{ form_widget(form.username,  {'attr': {'class': 'input-xxlarge'}})}}

        {{ form_label( form.email , 'email' | lower | trans | capitalize , {'attr': {'class': 'input-xxlarge' }}) }}
        {{ form_widget(form.email,  {'attr': {'class': 'input-xxlarge'}})}}

        <hr>

        {{ form_widget(form.plainPassword,  {'attr': {'class': 'input-xxlarge'}})}}

        <!-- roles -->

        <hr>
        <select id="roles" name="role" class="input-large">
        {% for role in roles %}
        <option value="{{role.role}}">{{role.role | trans  }}</option>
        {% endfor %}
        </select>





        <hr>
        <!--<div id="bootstrapped-fine-uploader"></div>-->


      {{ form_widget(form._token) }}

        </div>
        </fieldset>

    <button type="submit" class=" btn btn-primary pull-right" id="validate_section">{% trans %}save.changes{% endtrans %}</button>
    </form>




{% javascripts '@scrclubCMSBundle/Resources/public/js/cms/edit-user.js' filter='yui_js'  output='js/compiled/edit-user.js' %}
<script src="{{ asset_url }}"></script>
{% endjavascripts %}


{% endblock %}

Resources/views/cms/alert_lang_validate.html.twig
<div class="alert"><p>{% trans %}alert.validate.lang{% endtrans %}</p><p>{% trans %}wannado.this{% endtrans %}</p><button class="btn btn-small btn-danger avgrund-close " type="button" id="submit_lang">{% trans %}yes{% endtrans %}</button><button class="btn btn-small avgrund-close" type="button">{% trans %}no{% endtrans %}</button></div>

Resources/views/cms/categories.html.twig
{% extends "scrclubCMSBundle:cms:layout.html.twig" %}

{% block body %}

<div class="container">


    <div class="featurette row-liquid ">

        <h2 class="featurette-heading"><i class="icon-tags icon-1x"></i> {{ 'categories'| trans }} ({{categories | length }})
            <div class="muted featurette-sub-heading"</div>
        </h2>

    </div>




    <hr class="featurette-divider">

    <div class="row-fluid page-header">
        <div class="featurette">
            <a href="{{path('scrclub_cms_categories_add')}}" ><button class="btn btn-large pull-right" type="button"><i class="icon-plus"></i> {% trans %}add{% endtrans %} {% trans %}category{% endtrans %}</button></a>
        </div>
    </div>

    {% if categories|length > 0 %}


    <table class="table">
        <thead>
        <tr>
            <th>{{ "name" | trans | capitalize }}</th>

            <th style="text-align:right;">{{ "actions" | trans | capitalize }}</th>
        </tr>
        </thead>
        <tbody>


            {% for category in categories %}
        <tr id="{{category.id}}">
            <td>{{category.name}}</td>

            <td style="text-align:right;"><a href="{{path('scrclub_cms_categories_add', {id:category.id})}}" ><i class="icon-edit"> {{ "edit" | trans | capitalize }}</i></a> - <a href="#" class="remove-category"><i class="icon-trash"> {{ "delete" | trans | capitalize }}</i></a></td>
        </tr>
            {% endfor %}

        </tbody>
    </table>
    {% endif %}

</div>


<script>

var translations = {
    "wannado.this": "{{ 'wannado.this'| trans }} "
}

</script>
{% javascripts '@scrclubCMSBundle/Resources/public/js/cms/categories.js' filter='yui_js'  output='js/compiled/categories.js' %}
<script src="{{ asset_url }}"></script>
{% endjavascripts %}


{% endblock %}

Resources/views/cms/categories_add.html.twig
{% extends "scrclubCMSBundle:cms:layout.html.twig" %}

{% block body %}

<div class="container">


    <div class="featurette">
        <h2 class="featurette-heading">{{ 'categories'| trans }}
            <div class="muted featurette-sub-heading">--</div>
        </h2>
    </div>

    <hr class="featurette-divider">

    <form action="{{ path('scrclub_cms_categories_add', { 'id': category.id }) }}" method="post" {{ form_enctype(form) }} novalidate>

    {% set form_locales = form.translations.vars.locales %}
    {% set fields = form.translations.fields %}

    <div class="tabbable">
        <ul class="nav nav-tabs" id="langTab">


            {% for locale in form_locales %}


            {% set icon = '' %}

            {% if (form.translations.vars.default_locale[0] != locale)%}
            {% for translationForm in form.translations if (translationForm.vars.name == locale) %}

            {% if (translationForm.name.get('value') == "") %}

            {% set icon = '<i class="icon-warning-sign"></i>' %}

            {% endif %}
            {% endfor %}
            {% endif %}


            <li class="{% if (app.request.locale == locale) %} active {% endif %}">
                <a href="#{{locale}}" data-toggle="tab">{{icon | raw}} {{getLocaleName(locale,  app.request.locale  ) | capitalize }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class="tab-content">


        {% for locale in form_locales %}


        <div class="tab-pane x {% if (app.request.locale == locale) %} active {% endif %}" id="{{locale}}">

            <fieldset>
                <div class=" well control-group">
                    <div class="row-fluid">

                        {% if (form.translations.vars.default_locale[0] == locale) %}

                        <div class="span9">

                            {{ form_label( form.name , 'name' | lower | trans | capitalize , {'attr': {'class': 'input-xxlarge' }})
                            }}
                            {{ form_widget(form.name,  {'attr': {'class': 'input-xxlarge'}})}}


                            {{ form_label( form.description , 'description' | lower | trans | capitalize , {'attr': {'class': 'input-xxlarge' }})
                            }}
                            {{ form_widget(form.description,  {'attr': {'class': 'input-xxlarge'}})}}


                        </div>

                        {% else %}

                        {% for translationForm in form.translations if (translationForm.vars.name == locale) %}

                        <div class="span9">

                            {% for f in translationForm.children %}

                            {{ form_label( f , f.name | lower | trans | capitalize , {'attr': {'class': 'input-xxlarge' }})
                            }}
                            {{ form_widget(f,  {'attr': {'class': 'input-xxlarge'}})}}

                            {% endfor %}

                        </div>

                        {% endfor %}

                        {% endif %}

                    </div>
                </div>
            </fieldset>

        </div>
        {% endfor %}
    </div>

        {{ form_widget(form._token) }}
        <button type="submit" class=" btn btn-primary pull-right" id="validate_section">{% trans %}save.changes{% endtrans %}</button>
    </form>



</div>






{% endblock %}

Resources/views/cms/config.html.twig
{% extends "scrclubCMSBundle:cms:layout.html.twig" %}

{% block body %}


<div class="container">
    <div class="row">
        <div class="span2 ">
            <ul class="nav nav-list bs-docs-sidenav affix-top"  id="leftmenu">
                <li {% if app.request.attributes.get('_route') == 'scrclub_cms_config' %}class="active"{% endif %}><a href="{{path('scrclub_cms_config')}}"><i class="icon-chevron-right"></i> {{ 'your.site'| trans | capitalize }}</a></li>
                <li {% if app.request.attributes.get('_route') == 'scrclub_cms_langs' %}class="active"{% endif %}><a href="{{path('scrclub_cms_langs')}}"><i class="icon-chevron-right"></i> {{ 'langs'| trans | capitalize }}</a></li>

                <li {% if app.request.attributes.get('_route') == 'scrclub_cms_users' %}class="active"{% endif %}><a href="{{path('scrclub_cms_users')}}"><i class="icon-chevron-right"></i> {{ 'users'| trans | capitalize }}</a></li>
                <li {% if app.request.attributes.get('_route') == 'scrclub_cms_templates' %}class="active"{% endif %}><a href="{{path('scrclub_cms_templates')}}"><i class="icon-chevron-right"></i> {{ 'templates'| trans | capitalize }}</a></li>
                <li {% if app.request.attributes.get('_route') == 'scrclub_cms_analytics' %}class="active"{% endif %}><a href="{{path('scrclub_cms_analytics')}}"><i class="icon-chevron-right"></i> {{ 'analytics'| trans | capitalize }}</a></li>


            </ul>
        </div>
        <div class="span10">
                <div class="tab-content">
                    {% block sub_body %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /container -->

<script>

    var translations = {
        "wannado.this": "{{ 'wannado.this'| trans }}",
        "choose.lang" : "{{ 'choose.lang'| trans }}",
        "status" : "{{ 'status'| trans }}",
        "update.success" : "{{ 'update.success'| trans }}"
    }
    var alertTemplate = '{% include 'scrclubCMSBundle:cms:alert_lang_validate.html.twig'  %}';
    var updateLangUrl = "{{ path('update_langs') }}";

</script>

{% javascripts '@scrclubCMSBundle/Resources/public/js/cms/config.js' filter='yui_js'  output='js/compiled/config.js' %}
<script src="{{ asset_url }}"></script>
{% endjavascripts %}

{% endblock %}

Resources/views/cms/layout.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>SNUT</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    {% include 'scrclubCMSBundle:cms:_include.html.twig' %}

</head>

<body>


{% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
    {% embed "scrclubCMSBundle:cms:upmenu.html.twig" %}{% endembed %}
{% endif %}

<div class="container">
    {% block fos_user_content %}{% endblock %}
</div>

{% block body %}{% endblock %}

<div class="container">
    <hr>
</div>

<script>
    function newAlert(type, message) {
        $("#alert-area").append($("<div class='featurette alert-box fade in'><div class='alert alert-" + type + "' data-alert<p> " + message + " </p></div></div>"));
        $(".alert-box").delay(5000).fadeOut("slow", function () {
            $(this).remove();
        });
    }
</script>


</body>
</html>

Resources/views/cms/list_image.html.twig
<li class="span2 media-{{mediaNode.getMedia().id}}"  id="{{mediaNode.id}}">


    <div class="thumbnail">

        {% set media = mediaNode.getMedia() %}

        {% set updatePath = path('scrclub_cms_updateMediaPopOver', {id:mediaNode.media.id}) %}
        {% if (media.type =='image' )%}
        {% set iconClass = 'icon-picture' %}
        {% elseif (media.type =='document' )%}
        {% set iconClass = 'icon-file-alt' %}
        {% elseif (media.type =='embedded' )%}
        {% set updatePath =  path('scrclub_cms_updateEmbedPopOver', {id:mediaNode.media.id, mediasetId:mediaset.id}) %}
        {% set iconClass = 'icon-globe' %}
        {% endif %}


        <span class="label label-{{getSizeColor(media.fileSize)}}" style="position:absolute"><i class="{{iconClass}}"></i> {{media.extension}} {% if (media.type !='embedded' )%}- {{toMo(media.fileSize)}}{% endif %} </span>

        {% if (media.type =='image' )%}
        <img class="img-thumb-cms" style="height:140px" data-src="holder.js/130x140/text:{{media.name}}" {% if (media.getWebPath() != "" )%}src="{{asset(media.getWebPath()  | apply_filter('cms_user_thumb') )}}"{% endif %} alt="">

        {% elseif (media.type =='embedded' ) %}

        <img class="img-thumb-cms" style="height:140px" data-src="holder.js/130x140/text:{{media.name}}" src="{{ getThumbnail(media)  }}" alt="">
        <i class="icon-play-circle layer-thumb icon-2x"></i>


        {% else %}
        <img class="img-thumb-cms" data-src="holder.js/130x140/text:{{media.name}}" alt="">

        {% endif %}

        <hr>

        <p class="edit-media">
            <a data-mediaid="{{mediaNode.media.id}}"  data-medianodeid="{{mediaNode.id}}"  href="{{updatePath}}" data-target="#media-edit-modal"><i class=" icon-edit"></i>
                {{ 'edit'| trans | capitalize }}</a></p>
        <p class="remove-media"><a><i class=" icon-trash"></i> Remove</a></p>
    </div>
</li>

Resources/views/cms/posts.html.twig
{% extends "scrclubCMSBundle:cms:layout.html.twig" %}



{% block body %}

{% javascripts '@scrclubCMSBundle/Resources/public/js/cms/edit-post.js' filter='yui_js'  output='js/compiled/cms.js' %}
<script src="{{ asset_url }}"></script>
{% endjavascripts %}

<div class="container">

    <a href="#">home</a>
    {% if node.parent  %}{% include 'scrclubCMSBundle:cms:node_nav.html.twig' with {'node':node.parent, 'level':0 } %}{% endif %}

    <!-- got to node -->
    <div class="nav-collapse">
        <ul class="nav">
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle active" href="#">Go To <b class="caret"></b></a>
                {% include 'scrclubCMSBundle:cms:nodeMenuChildren.html.twig' with {'tree':rootTree, 'level':0 } %}
            </li>
        </ul>
    </div>

    <div class="featurette">
        <h2 class="featurette-heading">{{ 'section'| trans | capitalize }} {{ nodeParent.name }}</h2>
        <div class="muted featurette-sub-heading">{{tree | length}} {{ 'post'| trans  }}</div>
    </div>

    <hr class="featurette-divider">



    {% if form.get('errors') is not empty %}
    <div class="row-fluid page-header">
        <div class="featurette">
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Error!</strong> {{form_errors(form)}}
            </div>
        </div>
    </div>
    {% endif %}

    <hr class="featurette-divider">

    <div class="row-fluid page-header">
        <div class="featurette">
            <a href="{{path('scrclub_cms_addpost', { 'parent_id': nodeParent.id })}}" ><button class="btn btn-large pull-right" type="button"><i class="icon-plus"></i> {% trans %}add{% endtrans %} {% trans %}post{% endtrans %}</button></a>
        </div>
    </div>
    <div id="alert-area"></div>



    {% include 'scrclubCMSBundle:cms:nodeChildren.html.twig' with {'tree':tree, 'level':0 } %}

    <hr>




</div>
<!-- /container -->


<script src="{{ asset('js/jquery.mjs.nestedSortable.js') }}"></script>

<script>

    $(document).ready(function () {


        $('.sortable').nestedSortable({

            handle              :   'div',
            helper              :   'clone',
            items               :   'li',
            rootID              :   'root',
            opacity             :   1,
            tolerance           :   'pointer',
            placeholder         :   "placeholder",
            forcePlaceholderSize:   true,

            update              :   function (event, ui) {

                                    var arraied = $('.sortable').nestedSortable('toArray', {startDepthCount:0});
                                        $.ajax({
                                            type :'post',
                                            cache:false,
                                            url  :'{{ path('scrclub_cms_editnodetree') }}',
                                            data :{data:arraied},
                                            success: function(data){
                                            }
                                        });


                                    }

        });




    });



    jQuery('.submenu').hover(function () {
        jQuery(this).children('ul').removeClass('submenu-hide').addClass('submenu-show');
    },function () {
        jQuery(this).children('ul').removeClass('.submenu-show').addClass('submenu-hide');
    }).find("a:first").append(" &raquo; ");


    $(function () {

        $('.delete_node' ).each(function() {

            $(this).click(function () {

                var li = $($(this).parents().get()[4]);
                var id = li.attr('id').slice(5);



                bootbox.confirm("{{ 'wannado.this' | trans }}", function(result) {

                    if (result) {
                        $.ajax({
                            type :'post',
                            cache:false,
                            url  :'{{ path('scrclub_cms_deletenode')}}',
                            data :{data:id},
                            success: function(data){
                                newAlert("success", "{{ 'delete.success' | trans }}");
                                li.remove();
                            }
                        });
                    }
                });
            })
        });

        $('.switch-active' ).each(function() {

            $(this).on('switch-change', function (e, data) {

                var li = $($(this).parents().get()[1]);
                var id = li.attr('id').slice(5);

                var result = {
                    id : id,
                    active:data.value
                }

                $.ajax({
                    type :'post',
                    cache:false,
                    url  :'{{ path('scrclub_cms_updateActiveNode')}}',
                    data :result,
                    success: function(data){
                        //newAlert("success", "{{ 'update.success' | trans }}");
                    }
                });
            })
        });

    })

</script>




</script>



{% endblock %}